name: Publish Corvus
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    # Run on tagged releases
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - name: Upload to PyPi
        env:
         TWINE_USERNAME: '__token__'
         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
         poetry publish --build -u $TWINE_USERNAME -p $TWINE_PASSWORD
